

### 1) Import Pandas

In [ ]:
import pandas as pd

### 2) Import the dataset and  Assign it to a variable called users and use the 'user_id' as index

Use the following dataset
https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user

In [ ]:
users = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user', sep='|', index_col='user_id')

### 3) Display the first 25 entries

In [ ]:
print(users.head(25))

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

### 4) Display the last 10 entries

In [ ]:
users.tail(10)

         age gender     occupation zip_code
user_id
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

### 5) What is the number of observations in the dataset?

In [ ]:
len(users)

943

### 6) What is the number of columns in the dataset, also print the name of all the columns?

In [ ]:
col=users.columns
print(len(col))
print(col)

4
Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

### 7) What is the data type of each column?

In [ ]:
print(users.dtypes)

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

### 8) Print only the occupation column

In [ ]:
print(users['occupation'])

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

### 9) How many different occupations are in this dataset?

In [ ]:
x=users['occupation'].unique()
print(len(x))

21

### 10) What is the most frequent occupation?

In [ ]:
x=users['occupation'].value_counts()
x.head(1)

occupation
student    196
Name: count, dtype: int64

### 11) Summarize the DataFrame.

In [ ]:
users.describe()

              age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

### 12) Summarize only the occupation column

In [ ]:
users['occupation'].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### 13) What is the mean age of users?

In [ ]:
users['age'].mean()

np.float64(34.05196182396607)

### 14) What is the age with least occurrence?

In [ ]:
x=users['age']
f=x.value_counts(ascending=True)
print(x.head(1))

user_id
1    24
Name: age, dtype: int64

### 15) What is the zip code with most occurrence?

In [ ]:
x=users['zip_code']
f=x.value_counts(ascending=False)
print(f.head(1))

zip_code
55414    9
Name: count, dtype: int64

### 16) Which profession has youngest people(apart from student)? Show the trend of mean age of people with profession as the seperating factor.

In [ ]:
age=users.groupby('occupation')['age'].mean()
nostu_age=age.drop('student')
fen=nostu_age.value_counts()
print(fen.head(1))

age
38.746835    1
Name: count, dtype: int64